[package]
name = "super-remote-launcher"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "super-remote"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
base64.workspace = true
jsonwebtoken = { version = "10.0", features = ["rust_crypto"] }
qrcode = { version = "0.14", default-features = false, features = ["svg"] }
rand.workspace = true
serde.workspace = true
serde_json.workspace = true

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = [
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
  "Win32_NetworkManagement_IpHelper",
  "Win32_NetworkManagement_Ndis",
  "Win32_Networking_WinSock",
  "Win32_System_Threading",
  "Win32_UI_HiDpi",
  "Win32_UI_Shell",
  "Win32_UI_WindowsAndMessaging",
] }
